name: Compile and upload résumé PDF

on:
  push:
    branches: [ "main" ]
    paths:
      - "resume.tex"
      - "index.html"
      - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "resume.tex"
      - "index.html"
      - ".github/workflows/**"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Post Processing
        run: |
          mkdir build
          cp *.pdf build/
          cp index.html build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: build

  deploy:
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
          clean: true
